#import "../lib.typ": *

= Constraints and stack

Most design decisions in Code Share follow from a small number of constraints. Each constraint
excludes an otherwise obvious solution, and they are therefore stated here before the design.

== A free Apple developer account

The app is not distributed through the App Store, so the paid programme (\$99 per year) was not
purchased. A free _Personal Team_ (the same team used by the holy-shit iOS app) can sign and
sideload builds onto the owner's own phones, subject to the following limits:

#dtable(
  columns: (auto, 1fr, 1.2fr),
  header: ("Missing", "Would have been used for", "What Code Share does instead"),
  [Push (APNs)], [Notifying the other members' phones that a code was added or used], [Sync on foreground, 2 s after an edit, on pull-to-refresh],
  [Sign in with Apple], [Accounts], [Passkeys on a server-hosted page in `ASWebAuthenticationSession` (the holy-shit approach)],
  [Associated Domains], [Native passkey APIs bound to the domain], [Same page-based flow, custom URL scheme callback],
  [iCloud / CloudKit], [Syncing without a backend], [Own Go backend],
  [TestFlight], [Distributing to other members' phones], [Sideload; builds expire after *7 days* and must be reinstalled],
  [App Groups (unverified)], [Database shared with widget and share extension], [Entitlement added; whether a free team can provision it remains to be checked in Xcode],
)

The seven-day expiry is more consequential than it appears. Any build on a phone is at most one
week old, so there is no long tail of old app versions requiring compatibility. A short tail does
exist, however, and @sec-wipe describes a case in which an old build on one phone constrained a
server change.

== Platform floor and appearance

The phones run iOS 18 and iOS 26, but the code is kept portable to *iOS 16*, the minimum version
of VisionKit's `DataScannerViewController`. This excludes several recent APIs:

- `ObservableObject` and `@Published` are used instead of the `@Observable` macro (iOS 17).
- SwiftData (iOS 17) is not available; together with the reasons given in @sec-grdb, this led
  to SQLite via GRDB.
- The single-argument `onChange(of:)` is used, because the two-argument form requires iOS 17.

*No Liquid Glass.* `ios/Config/Info.plist` sets `UIDesignRequiresCompatibility`, so on iOS 26
the app retains the iOS 18 appearance, as holy-shit-ios does. This file is merged with the
generated plist, which also declares the `codeshare://` URL scheme.

== A shared server

The backend runs on a single FreeBSD machine that already serves other production applications
(the author's other projects). The machine is managed by Ansible in a separate
repository, `shared-infrastructure`, which also contains Terraform/terragrunt units for the AWS
resources of each project (CloudWatch logs and error e-mails, S3 backups). Because the project is
one tenant on a shared production host, operations follow a conservative procedure: dry runs
first, changes confined to the project's own resources, reload rather than restart, and
verification of the neighbouring services afterwards (Chapter 8).

The shared host also constrained the backend: no Docker, a single static binary, and a PostgreSQL
instance shared with the other applications (so unauthenticated endpoints must not be able to
exhaust its disk).

== The stack

#dtable(
  columns: (auto, 1fr),
  header: ("Layer", "Choice and reason"),
  [iOS UI], [SwiftUI, `ObservableObject`, `NavigationStack(path:)` with a `Route` enum. All colours, fonts, spacing in `Views/Theme.swift`.],
  [Local store], [SQLite through *GRDB.swift* 7 (plain SQL migrations, `ValueObservation`). The only SPM dependency.],
  [Scanning], [VisionKit `DataScannerViewController` (live), Vision `VNDetectBarcodesRequest` + `VNRecognizeTextRequest` (photos).],
  [Crypto], [CryptoKit only: HKDF-SHA256, ChaChaPoly, HMAC-SHA256, ECDH in the Secure Enclave on NIST P-256 (secp256r1), referred to in this document as the glowie curve#footnote[“Glowie” is internet slang for intelligence-agency personnel, popularised by Terry A. Davis, the author of TempleOS, who claimed he could spot federal agents because they “glow in the dark”. The name refers to the curve's provenance. P-256's parameters were generated by the NSA from a seed whose origin was never explained, so the generation could in principle have been steered; SafeCurves rates the curve “manipulable”. The NSA-designed Dual\_EC\_DRBG random-number generator, built on P-256 points with unexplained constants, was shown in 2013 to be backdoored. No practical weakness of P-256 itself is known after more than 25 years of use, and it underlies the Secure Enclave, WebAuthn (ES256) and most TLS deployments. Curve25519, by contrast, has rigid parameters with a published derivation. The project accepted P-256 because hardware-bound Secure Enclave keys exist only on that curve.].],
  [Backend], [Go 1.27, *Echo v5*, pgx/v5, sqlc, goose, slog, mise tasks, air. OpenAPI 3 contract → oapi-codegen strict server.],
  [Database], [PostgreSQL 18 (native `uuidv7()`, `xid8`).],
  [Geocoding], [MapKit on the phone (no key); PDOK Locatieserver on the server (free Dutch government geocoder).],
  [Ops], [Ansible (deploy and provisioning), Caddy (TLS), Terraform/terragrunt (AWS), OTLP to CloudWatch.],
)

== Adopted conventions and one departure

Two sibling projects served as references: `holy-shit-ios` (SwiftUI) and `holy-shit-api` (Go).
The backend adopts holy-shit-api's toolchain, telemetry package, passkey flow, deploy scripts and
mise tasks almost verbatim. The two code bases are intentionally "kept diffable", so that a fix in
one can be ported to the other. The iOS app adopts holy-shit-ios's `AuthService` and onboarding
flow.

The one intentional departure is the backend *layering*. In holy-shit-api, handlers call sqlc
directly. Code Share places a service layer (business rules, transactions) and a repository layer
(multi-table queries) between the generated handlers and the database. This decision was taken by
the owner before any code was written, on the grounds that the household, key-wrap and sync rules
are too intricate to reside in handlers.

#lesson[A stack is verified from the code, not from its description. The GitHub description of
holy-shit-api stated ASP.NET; the code is Go. The plan adopts conventions from what the repository
actually contains, and `CLAUDE.md` now states this explicitly.]
