#import "../lib.typ": *

= Any code: generic codes and boarding passes <sec-any-code>

Also a *specification*. The app so far understands the codes it was built for: vouchers, the
Bonuskaart and, as specified, parking tags. Two further requirements widen this: *any* QR code or
barcode can be stored without questions, and old boarding passes can be imported.

== Generic codes, no questions asked <sec-generic>

A generic code is whatever the camera or a picture yields that no chain's rules claim. The rule
for it is that saving never stops to ask:

- *Saved on sight.* In the scanner, a detected code that no rule claims is saved at once as kind
  `generic`, with a haptic tick and an undo banner instead of a confirmation form. A picture or
  file with several codes saves each of them.
- *Label without input.* The label defaults to the first line of the decoded text, up to 40
  characters, or to the symbology and date ("QR · 5 Oct 2026") when the payload is not text. It can
  be edited later, never before saving.
- *Duplicates are silent.* Payloads are unique (@sec-grdb); scanning a stored code again shows the
  existing one, revived if it was deleted.
- *Content is inert.* A URL, Wi-Fi configuration or contact card in a code is shown as text and
  never opened, joined or imported by the app. A code is something to *show*, not to follow.
- *Reclassify later.* A generic code can be turned into a voucher or parking tag afterwards, which
  runs the chain's parser on the stored payload and photo text, if any.

=== Payload and symbologies

Vision detects far more symbologies than the app renders. Each stored code keeps its symbology
and the *exact payload*: the string where the code holds text, and the raw bytes
(`VNBarcodeObservation.payloadData`) where it holds binary data, so that a regenerated code
carries the same bytes, not a re-encoding of a lossy string.

#dtable(
  columns: (1fr, 1.4fr),
  header: ("Symbologies", "Display"),
  [QR, Aztec, PDF417, Code 128], [Regenerated by CoreImage, with the rendering rules of @sec-ean13.],
  [EAN-13 (built), EAN-8, UPC-A, UPC-E, ITF, Code 39, Code 93, Codabar], [Regenerated by the app: linear symbologies are a table and a loop each, as `EAN13.swift` shows.],
  [Data Matrix, GS1 DataBar, Micro QR, MicroPDF417 and anything newer], [Not regenerated. The app stores a cropped, deskewed, binarised image of the symbol, at most 12 KiB, so the sealed blob stays under its 16 KiB limit (@sec-sealed-meta).],
)

A payload larger than the sealed limit allows (a QR holds at most about 3 KB, so this is
theoretical for barcodes) is refused with a message, the one case where saving can fail.

== Boarding passes <sec-boarding>

Boarding passes are the commonest codes after vouchers that a household holds and loses: on
paper, in PDFs attached to e-mails, in Apple Wallet, in screenshots. The requirement is to
*import old ones*: as a record of trips, and as a place where a pass can be found again.

=== What the barcode contains

Nearly every airline encodes its pass to IATA's *Bar Coded Boarding Pass* standard (BCBP,
Resolution 792): a fixed-width text in PDF417 on paper, Aztec or QR on phones, sometimes Data
Matrix. Its mandatory part is 60 characters; an example with fictitious values:

#align(center, block(fill: c.panel, inset: (x: 3mm, y: 2mm), radius: 2pt,
  text(font: mono-font, size: 7.4pt, fill: c.text)[`M1DOE/JANE            EABC123 AMSBERXX 0123 278Y012A0042 100`]))

#dtable(
  columns: (auto, auto, auto, 1fr),
  header: ("Chars", "Width", "Example", "Field"),
  [1], [1], [`M`], [Format code.],
  [2], [1], [`1`], [Number of legs encoded (one barcode can hold several flights).],
  [3–22], [20], [`DOE/JANE`], [Passenger name, surname first.],
  [23], [1], [`E`], [Electronic ticket indicator.],
  [24–30], [7], [`ABC123`], [Booking reference (PNR).],
  [31–36], [3 + 3], [`AMS` `BER`], [From and to airports.],
  [37–39], [3], [`XX`], [Operating carrier.],
  [40–44], [5], [`0123`], [Flight number.],
  [45–47], [3], [`278`], [Date of flight as day of the year, *without a year* (278 is 5 October in a common year).],
  [48], [1], [`Y`], [Compartment (class).],
  [49–52], [4], [`012A`], [Seat.],
  [53–57], [5], [`0042`], [Check-in sequence number.],
  [58], [1], [`1`], [Passenger status.],
  [59–60], [2], [`00`], [Length of the conditional section that follows, in hexadecimal.],
)

The conditional section (version, issue date, baggage tags, frequent-flyer number and more)
and an airline's security data may follow. The fields of further legs repeat the block from
the PNR onwards.

=== The year

The flight date has no year. Old passes make this the main parsing problem. In order of trust:

+ The *issue date* in the conditional section, where present: the last digit of the year plus the
  day of the year. It fixes the year within a ten-year window, and the flight lies on or after it.
+ A *date from the container*: a Wallet pass's `relevantDate`, a PDF's creation date, a
  photo's capture date. The flight is the date with that day number nearest to it.
+ Neither: the most recent past year in which the day exists. The year is shown as inferred and
  can be corrected.

Leap years shift every day number from 60 (29 February) on, so the year must be fixed before the day number is
turned into a date.

=== Import sources

#dtable(
  columns: (auto, 1fr),
  header: ("Source", "How"),
  [PDF (e-mail attachment, airline download)], [PDFKit renders each page at high resolution; `VNDetectBarcodesRequest` finds the PDF417 or Aztec code. The page's text supplies departure time and gate if wanted.],
  [Wallet pass file (`.pkpass`)], [A zip archive; `pass.json` holds `barcodes[].message`, `format` and `messageEncoding`. The payload is read directly, no image decoding, and the file's `relevantDate` serves the year.],
  [Apple Wallet itself], [Not readable: PassKit lets an app read only its own team's passes. A pass is exported with Wallet's share button, where the airline permits it, or the original `.pkpass` from the e-mail is used.],
  [Screenshot, photo of a paper pass], [The existing photo import (@sec-widget) with PDF417, Aztec, QR and Data Matrix enabled.],
  [Many at once], [The share extension and a file picker accept several PDFs, passes and pictures, and a folder of old ones; each code found is saved (@sec-generic), passes parsed as below.],
)

=== How a pass is stored

- *Kind* `boarding`. The payload is the barcode text, byte for byte, security data included.
- *Dates.* `issuedAt` is the departure date; a pass whose flight is in the past is imported as used
  ("flown"), so old passes do not crowd the home screen. They live in a "Trips" list, by date.
- *No store.* Airports and flights live *only in the sealed content*, as parking locations do
  (@sec-parking): a travel history is more revealing than a bike's position, and the server
  needs none of it.
- *Display.* Route, date, flight and seat parsed from the payload, and the code regenerated in its
  symbology. A non-BCBP code from an airline or rail company is kept as a generic code with the
  container's metadata as its label.

#warn(title: "Sharing a boarding pass")[A BCBP barcode contains the passenger's name and the
booking reference. With the two, anyone can open the booking on most airline websites, change
it or cancel it. A pass's code screen therefore never leaves the app silently: the share
button for a `boarding` code shows what the barcode contains before sharing, and the share
template prints the route and date but blanks the PNR in the text. The barcode itself
necessarily contains it.]

== Open questions

- *Gate scanners.* Whether a regenerated PDF417 or Aztec code is accepted at a gate is irrelevant
  for old passes and untested for current ones; current passes belong in Wallet.
- *Rail.* Rail tickets use other standards (UIC 918.3 Aztec with signatures, e.g. Deutsche Bahn);
  they are stored as generic codes until someone needs more.
- *Trips.* Whether the "Trips" list is worth more than a filtered view of `boarding` codes.
